In [34]:
# !pip install numpy


In [35]:
import numpy as np
import math

In [36]:
a = np.array([[1, 2, 3],[4, 5, 6]])
a.shape

(2, 3)

In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [38]:
a[:3]

array([1, 2, 3])

In [39]:
# b = np.array([1, 2, 3, 4, 5, 6])
b = a[3:]
b
b[0] = 40
a

array([ 1,  2,  3, 40,  5,  6])

In [40]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[1, 3]

np.int64(8)

### Array attributes

In [41]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [42]:
a.ndim

2

In [43]:
a.shape

(3, 4)

In [44]:
print(len(a.shape))

2


In [45]:
a.size

12

In [ ]:
a.size == math.prod(a.shape)

True

In [47]:
a.dtype

dtype('int64')

### How to create a basic array

This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()



In [49]:
np.zeros(2)

array([0., 0.])

In [50]:
np.ones(2)

array([1., 1.])

In [53]:
np.empty(2)

array([1.34126315e-313, 1.16568549e+253])

In [ ]:
np.arange(4)


In [ ]:
np.arange(2, 9, 2)


In [ ]:
np.linspace(0, 10, num=5)


In [ ]:
x = np.ones(2, dtype=np.int64)


### Adding, removing, and sorting elements

This section covers np.sort(), np.concatenate()



In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])